name: Deploy Hooks to Render

on:
  push:
    paths:
      - "apps/hooks/**"
      - "packages/db/**"
      - ".github/workflows/deploy-hooks.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Render Deploy Hook
        run: echo "Render Hook = '${{ secrets.RENDER_DEPLOY_HOOK }}'"

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
